Feat: streams
Adamant-im/ipfs-node pull request #4
Opened 2024-05-04 12:09 UTC by PaulDremanovich

Task: [Initial version of IPFS node](https://trello.com/c/d1iMesi5/386-initial-version-of-ipfs-node)

Completed items:
- Modify `POST /file/upload` as it can upload files using streams or use other storage than [multer.MemoryStorage](https://expressjs.com/en/resources/middleware/multer.html). Currently uploading large files may cause running out of memory. Also add `maxFileSize` to the config.
- Rewrite `GET /file/:cid` using streams
- Move the request timeout of `GET /file/:cid` to the config file.

2024-05-04 12:11 UTC, PaulDremanovich commented
![](https://github.trello.services/images/mini-trello-icon.png) [Initial version of IPFS node](https://trello.com/c/d1iMesi5/386-initial-version-of-ipfs-node)

2024-05-07 15:58 UTC, bludnic requested changes

2024-05-07 15:58 UTC, bludnic commented on config.default.json5
> +  findFileTimeout: 30000
add comment in MB

2024-05-07 15:58 UTC, bludnic commented on src/index.ts
> +      console.log(`Adding ${file.originalName} to IPFS`)
use pino logger

2024-05-07 15:58 UTC, bludnic commented on src/multer.d.ts
> +}
Just install `@types/multer`. You don't need this file.
https://www.npmjs.com/package/@types/multer

```
npm i --save-dev @types/multer
```

2024-05-07 17:19 UTC, PaulDremanovich commented on src/multer.d.ts
> +}
There are no types yet for Multer version 2.0.0-rс4

2024-05-07 18:51 UTC, bludnic commented on src/multer.d.ts
> +}
Can you use `1.4.5-lts.1`? Or you need `2.0.0-rс4`?

![image](https://github.com/Adamant-im/ipfs-node/assets/25831507/36fcdbe6-29ae-494d-b083-a1b119d7237f)

2024-05-07 18:52 UTC, bludnic commented on config.default.json5
> +  uploadLimitSizeBytes: 268435456, //256 Mb.
add space -> `// 256 Mb.`

2024-05-07 18:53 UTC, bludnic commented on config.default.json5
> +  uploadLimitSizeBytes: 268435456, //256 Mb.
Check the linter/prettier. It should format this automatically, I think.

2024-05-08 21:02 UTC, RealGoodProgrammer approved these changes

2024-05-08 21:08 UTC, bludnic approved these changes

2024-05-09 20:26 UTC, merged