Refactor README.md
Adamant-im/ipfs-node pull request #9
Opened 2024-07-10 13:13 UTC by confleux

Consider the following changes to README.

As I've had to install ipfs nodes without knowing the project structure and working with it before, some times it wasn't clear how to set it up and use.

I propose these changes to make docs more structured, accurate and clear.

2024-07-10 14:38 UTC, bludnic requested changes

2024-07-10 14:38 UTC, bludnic commented on README.md
> +Keep-Alive: timeout=5
I think you can omit these headers to reduce noise in the README. They don't contain useful information. Maybe keep `Content-Type`.

2024-07-10 14:38 UTC, bludnic commented on README.md
> +  "availableSizeInMb":2257731
Please format the JSON. Add space after `:`

2024-07-10 15:55 UTC, bludnic approved these changes

2024-08-07 10:52 UTC, PaulDremanovich approved these changes

2024-08-10 10:27 UTC, merged